[versions]
kotlin = "2.3.0"
kctfork = "0.12.1"
junit5 = "6.0.3"

[libraries]
kctfork-core = { module = "dev.zacsweers.kctfork:core", version.ref = "kctfork" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
treant = { id = "com.adkhambek.treant" }
